### PR TITLE
Add device activity graphs

### PR DESCRIPTION
**Pull request by arthurmcgregor**
This PR is not ready for merging. It is simply to make the work in #119 visible to others for feedback

### CODE REVIEW

**Comment by mjs** [comment]
Thanks for this. I've run it on my machine and it looks great.

I've started a review and have feedback but today has been a bit nuts. I'll
get some detailed feedback to you this evening or tomorrow morning.

Some initial thoughts:

It works well with 10s of devices with recordings but will probably
struggle with 100s.
Maybe the graph will have to be scrollable?

A log scale or cap might be better for the y axis.

Will it be possible for the bars and labels to be clickable so that they
lead on to the query page for that device?

The query for 365 days is slow. Probably a server side issue though. We
should look at the queries involved

Instead of showing all the devices which didn't send a recording perhaps
show all that did send in the previous period but not in the current one?

Nice work anyway!

**Comment by CameronRP** [comment]
This all looks really good!
As Menno said being able to click on the graph to take you to a page with that devices recordings would be really nice. Don't know how easy this will be though. If we add URL params in the recordings page for the query that would make it much easier.

**Comment by mjs** [comment]
More feedback:

A better name in the nav bar might be "Analysis" or something.

Can we do without the Update Graph button so that the graph updates whenever the date range, device type or device group changes?

There needs to be a "last 24 hours" range. That would be a common use case.

I've had a quick scan of the code and nothing stands out. We can do a detailed code review once it's ready to land.

Thanks for tackling this and getting it working so quickly. This is very exciting stuff.

**Comment by arthurmcgregor** [comment]
Cool! Thanks for the feedback :-) Most of that should be do-able....

**Pull request closed without merging**
