### PR TITLE
Update Cacophony API calls to use a newly created HTTP abstraction to simplify code

### PR DESCRIPTION
**Pull request by jackodsteel**
Relies on #283 in cacophony-api to be deployed to allow the JSON requests to get passed CORS.

Created API abstraction to simplify code accessing the Cacophony API. This really simplifies the consumer code so they don't need to worry about serialisation or content types.

Switched to JSON objects instead of urlencoded as it's nicer to deal with.

Clean up the fetch method a bit to not have opaque inputs and to call crossFetch normally.

### CODE REVIEW

**Comment by mjs** [comment]
@hardiesoft you've been working in this direction too. Does this PR align with what you've been doing?

**Comment by hardiesoft** [comment]
I guess I'd say it doesn't not align with what I'm doing :-D
Reminds me a lot of the axios api.

I was also wondering why fetch was written that way - explicitly passing args there is definitely an improvement.

**Comment by mjs** [comment]
I must say the cacophonyApi.get/post/delete calls are much clearer and nicer to look at than the previous fetch calls.

@hardiesoft if this lands will it conflict badly with your work or are you happy to adapt?

@jackodsteel looks like you've got some small conflicts with master.

**Comment by hardiesoft** [comment]
I don't think it should conflict much, if at all, and if it does I'm sure it'll be easy to adjust.

**Comment by jackodsteel** [comment]
Cool!

Remember the note that the changes in this PR depend on TheCacophonyProject/cacophony-api#285 and TheCacophonyProject/cacophony-api#285, so this can't be deployed until that's actually up and running on the test/prod servers.

**Comment by mjs** [comment]
@jackodsteel understood but thanks for the reminder. Do all our releases together on Mondays so these changes will get deployed together.

**Pull request merged**
